### ISSUE TITLE
Add variability to the optical parameters

### ISSUE THREAD

**Issue by esheldon** [esheldon/psfsim_config#1]
According to @rmjarvis we can add variability within a chip this way, using astig1 as an example

```
astig1: 
    type: Eval
    str: "mean + a * image_pos.x + b * image_pos.y + c * image_pos.x**2 + d * image_pos.y**2 + e * image_pos.x*image_pos.y"
    fmean: { type: RandomGaussian, sigma: 0.13, index_key: file_num }
    fa: { type: RandomGaussian, sigma: 2.e-3, index_key: file_num }
    fb: { type: RandomGaussian, sigma: 2.e-3, index_key: file_num }
    fc: { type: RandomGaussian, sigma: 1.e-6, index_key: file_num }
    fd: { type: RandomGaussian, sigma: 1.e-6, index_key: file_num }
    fe: { type: RandomGaussian, sigma: 1.e-6, index_key: file_num }
```

these sigma are absolute sigmas, and because mean was not mentioned they
are at zero
